### PR TITLE
Untitled

### PR DESCRIPTION
**Pull request by kprevas**
Without this change, the DDL parser gives up as soon as it encounters something that isn't CREATE TABLE.  I don't think this change is perfect but it's a reasonable stopgap and it allows the Ronin sample app's schema to be parsed.

### CODE REVIEW

**Comment by akeefer** [comment]
What's the DDL file that blows up without these changes?  I'm currently converting the parser over to use Carson's tokenizer, which is a pretty significant change, so I want to make sure that when I convert the parser over to that approach that I don't just re-introduce the bug.  Could you perhaps add some test cases to the MySQL51SQLParserTest test class that test the issue so I don't break it?

**Comment by kprevas** [comment]
https://github.com/kprevas/ronin/blob/master/roblog/src/db/roblog.ddl

I made a parallel change to CreateTableParser, which I think is the new one you're working on.  I will gladly add a test or two to catch it, though.

**Comment by kprevas** [comment]
I don't know if you got a notification, but tests are in now.

**Comment by akeefer** [comment]
Nope, apparently adding some commits doesn't trigger a notification, so I didn't see it.  I'll try to pull the changes in today.

**Pull request merged**
