### PR TITLE
a few changes/fixes we had to do in order to release 0.1

### PR DESCRIPTION
**Pull request by bchang**

### CODE REVIEW

**Comment by akeefer** [comment]
Can I ask why you had to disable the tests?  They run fine for me locally . . .

**Comment by bchang** [comment]
That was Carson.  If he disabled them, maybe they weren't passing for him?  I had been finding with some of the other projects that the maven-release-plugin was attempting to run tests regardless of whether you used -DskipTests or -Dmaven.test.skip=true. I didn't deal with the Tosa tests directly, but Carson and I had both been looking around the open source projects forproblematic tests we could disable just to get them deployed via the release plugin.

**Comment by akeefer** [comment]
Ahhh, okay, I get it now.  Those are Java tests, but they don't run if Gosu isn't initialized, so they fail when run by Maven, even though they're fine if they're run in the context of TosaSuite (which is in Gosu).

**Comment by bchang** [comment]
Yeah, it's high on our list of priorities to be able to run Gosu tests with Maven.  I think Carson has come up with a couple ideas.

**Comment by 1cg** [comment]
My current proposal for Tosa is that we just write all our tests in Gosu and take advantage of the feature that Maven currently does not run them during its test phase.

**Pull request merged**
